### ISSUE TITLE
Fails in nodejs < 13

### ISSUE THREAD

**Issue by richardscarrott** [tpoisseau/js-pattern-matching#1]
Fails in nodejs with:

```
import returnValue from "./evaluators/returnValue.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/rich/Projects/parade/js-pattern-matching-test/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

Would you accept a PR to which exports a commonjs version?

**Comment by richardscarrott** [comment]
I think rollup is a good choice for a lib, e.g. https://github.com/rollup/rollup-starter-lib which offers 3 exports:

```json
// package.json
"main": "dist/how-long-till-lunch.cjs.js",
"module": "dist/how-long-till-lunch.esm.js",
"browser": "dist/how-long-till-lunch.umd.js",
```

**Comment by richardscarrott** [comment]
We're using a fork published as [@riscarrott/pattern-matching](https://www.npmjs.com/package/@riscarrott/pattern-matching) on Node 12 -- really like the library btw, cleaned up a bunch of code nicely.

I've not sent a PR as I had to hack it up to get the multiple exports working well with TypeScript due to this issue -- https://github.com/microsoft/TypeScript/issues/33079 so I doubt you'd want it in it's current state.

Code can be found here https://github.com/richardscarrott/js-pattern-matching/tree/rollup

**Comment by tpoisseau** [comment]
Hello,
Sorry I'm a bit long to respond.
It's a lib under MIT Licence so make what you want with the code ^^.

It should work with node 12, but with some flags to get it work with node ESM experiment.

Maybe I'll take some time later to check if the "export" section spec in package.json not changed in last nodejs version.

But, I'm not a fan of build tools for small libs and prefer to keep this lib with ESM module only.

They are specified since ES6 (5-6 years now) and experimental in Node.js since v12 and flag removed since v12.17.
I think its time to give up CJS now ^^.

This lib and doc is adapted to ESM and "export" package.json. And force to split the imports instead export all in index.js.

Please give me node version you use, i'll check what node flag should be use in this context for using this lib.

I'm happy to now this lib is used and appreciated !

Best regards

**Comment by richardscarrott** [comment]
We're on 12.14.0 so we could just as well upgrade to 12.7 without any issues I expect 👍 

We also use TypeScript however so the multiple exports are causing issues there due to  https://github.com/microsoft/TypeScript/issues/33079 -- I tested with typescript@4.1.3 -- not sure if TS is planning on fixing that 🤔
